SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\lib\jbcl.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\lib\dx.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\lib\beandt.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\jdk1.3.1\demo\jfc\Java2D\Java2Demo.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\jdk1.3.1\jre\lib\i18n.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\jdk1.3.1\jre\lib\jaws.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\jdk1.3.1\jre\lib\rt.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\jdk1.3.1\jre\lib\sunrsasign.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\jdk1.3.1\lib\dt.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\jdk1.3.1\lib\htmlconverter.jar"
SET CLASSPATH=%CLASSPATH%;"I:\Program Files\JBuilder7\jdk1.3.1\lib\tools.jar"
SET CLASSPATH=%CLASSPATH%;"D:\Dev\Travaux\Java\JBuilder7\HTTParser\lib"

"I:\Program Files\JBuilder7\jdk1.3.1\bin\javaw" -classpath %CLASSPATH% Main.class"
